
services:
  lms-admin:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: lms-admin

    restart: always

    working_dir: /app

    volumes:
      - /srv/lms-admin:/app

    labels:
      - "traefik.enable=true"

      # router
      - "traefik.http.routers.lms-admin.rule=Host(`adminlms.onlinify.ir`)"
      - "traefik.http.routers.lms-admin.entrypoints=websecure"
      - "traefik.http.routers.lms-admin.tls.certresolver=letsencrypt"
      - "traefik.http.routers.lms-admin.service=lms-admin"

      # service
      - "traefik.http.services.lms-admin.loadbalancer.server.port=80"

    networks:
      - proxy

networks:
  proxy:
    external: true
