server {
    listen 80;

    server_name bandargaz.sandoghedu.ir _;

    root /app/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico|woff|woff2)$ {
        expires 30d;
        access_log off;
    }
}